#!/usr/bin/env bash
# Shows information about subdomains.

display_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$3
    local destination=$4
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function
main() {
    local domain=$1
    local subdomain=$2

    # If subdomain is not provided, use default subdomains
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    # Loop through subdomains and display information
    for sub in "${subdomains[@]}"; do
        # Use dig command to get DNS information and awk to extract relevant data
        dns_info=$(dig $sub.$domain | awk '/^;; ANSWER SECTION:$/,/^$/' | grep -v '^;;' | awk '{print $1,$4}')
        record_type="A"
        destination=$(echo "$dns_info" | awk '{print $2}')
        display_info "$sub" "$domain" "$record_type" "$destination"
    done
}

# Check if domain argument is provided
if [ -z "$1" ]; then
    echo "Error: Domain name argument is missing."
    exit 1
fi

# Call main function with provided arguments
main "$@"
