#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server:
# Requirements:
# Accepts 4 parameters
# The path to the file to be transferred
# The IP of the server we want to transfer the file to
# The username scp connects with
# The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY-
# -if less than 3 parameters passed
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file to the server using scp
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully to $username@$ip:~/"
else
    echo "Failed to transfer file to $username@$ip:~/"
    exit 1
fi
