#!/usr/bin/env bash
# A script that runs 'whoami' as the specified user
sudo -u $1 whoami
# Requirements:

# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
# make sure to try your script by passing different users.
# Check if a user name is provided

# Run the whoami command as the specified user
# sudo -u $1 whoami
