#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

# Requirements:

# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Write a Bash script that configures the container to fit the above requirements
# Set nginx user in nginx.conf
sed -i 's/^user .*$/user nginx;/g' /etc/nginx/nginx.conf

# Set nginx to listen on port 8080 for all IPs
sed -i 's/^listen       80;/listen       8080;/g' /etc/nginx/sites-available/default

# Restart nginx service to apply changes
service nginx restart
